export const projects = [
  {
    title: "Sumber Alam Bali",
    desc: "Company Profile Toko Batu Alam",
    url: "http://www.sumberalambali.com",
    tech: ["React"],
    pic: "sumberalam.jpeg",
  },
  {
    title: "Wedding Invitation",
    desc: "Undangan Pernikahan Online",
    url: "https://undanganku.github.io/vinosyofi/",
    tech: ["React"],
    pic: "undanganku.jpeg",
  },
  {
    title: "Mini Wordpress",
    desc: "Simple CRUD Wordpress",
    url: "",
    tech: ["Vue"],
    pic: "",
  },
  {
    title: "Rumah Tani",
    desc: "Rumah Tani Website",
    url: "",
    tech: ["Vue", "Node Js"],
    pic: "",
  },
  {
    title: "Bercerita",
    desc: "E-Book App",
    url: "",
    tech: ["React Native"],
    pic: "",
  },
  {
    title: "Password Manager",
    desc: "Manage password website",
    url: "",
    tech: ["React js"],
    pic: "",
  },
  {
    title: "Coffee Me",
    desc: "E-Commerce Coffee shop",
    url: "",
    tech: ["Vue"],
    pic: "",
  },
  {
    title: "KanBan",
    desc: "Visual Board to manage your work",
    url: "",
    tech: ["React"],
    pic: "",
  },
];
