export const projects = [
  {
    title: "Kode Cinta",
    desc: "Website Undangan Pernikahan Digital",
    url: "https://www.kodecinta.com/",
    tech: ["Next Js", "CSS", "Google Analytics", "Responsive"],
    pic: "kodecinta.jpeg",
  },
  {
    title: "Klob.id B2C",
    desc: "Cari Lowongan Pekerjaan yang Klob hanya di Klob!",
    url: "https://www.klob.id/",
    tech: ["React Js", "CSS", "AWS", "Google Analytics", "Responsive"],
    pic: "klob.jpeg",
  },
  {
    title: "Klob.id B2B",
    desc: "Solusi rekrutmen dan asesmen digital untuk mencari talenta terbaik bagi perusahaan Anda",
    url: "https://employers.klob.id/",
    tech: ["React Js", "CSS", "Google Analytics", "AWS"],
    pic: "employers-klob.jpeg",
  },
  {
    title: "Klob.id Admin",
    desc: "CMS admin page untuk mengelola platform Klob.id",
    url: "https://setting.klob.id/",
    tech: ["React Js", "CSS"],
    pic: "admin-klob.jpeg",
  },
  {
    title: "NPM klob-ui-components",
    desc: "klob-ui-components is a package that provides a set of reusable UI components for building user interfaces in web applications.",
    url: "https://www.npmjs.com/package/klob-ui-components",
    tech: ["React Js", "CSS", "NPM"],
    pic: "klob-ui-components.jpeg",
  },
  {
    title: "Intelligo",
    desc: "Intelligo memberikan kesempatan kepada setiap orang untuk menjadi seorang pemimpin melalui pengembangan kemampuan teknis maupun nonteknis di bidang IT",
    url: "https://intelligo.klob.id/",
    tech: ["React Js", "CSS", "Google Analytics", "Responsive"],
    pic: "intelligo-klob.jpeg",
  },
  {
    title: "admin-intelligo",
    desc: "CMS admin page untuk mengelola platform Intelligo",
    url: "https://admin.intelligo.klob.id/",
    tech: ["React Js", "CSS", "Responsive"],
    pic: "admin-intelligo.jpeg",
  },
  {
    title: "Sumber Alam Bali",
    desc: "Company Profile Toko Batu Alam",
    url: "https://sumberalambali.vercel.app/",
    tech: ["Next Js", "Tailwind", "Google Analytics", "Responsive"],
    pic: "sumberalam.jpeg",
  },
  {
    title: "Game Batu Gunting Kertas",
    desc: "Game Sederhana Batu Gunting Kertas",
    url: "https://srpw-project.github.io/batu-gunting-kertas/",
    tech: ["React Js", "CSS", "Responsive"],
    pic: "batu-gunting-kertas.jpeg",
  },
  {
    title: "Sumber Alam Bali",
    desc: "Company Profile Toko Batu Alam",
    url: "http://www.sumberalambali.com",
    tech: ["React Js", "CSS", "Responsive"],
    pic: "sumberalam.jpeg",
  },
  {
    title: "Wedding Invitation",
    desc: "Undangan Pernikahan Online",
    url: "https://undanganku.github.io/vinosyofi/",
    tech: ["React Js", "CSS", "Responsive"],
    pic: "undanganku.jpeg",
  },

  {
    title: "Rumah Tani",
    desc: "Rumah Tani is a E-Commerce Website",
    url: "",
    tech: ["Vue", "Node Js", "Responsive"],
    pic: "rumah-tani.jpeg",
  },

  {
    title: "Minimum",
    desc: "Minimum is a mini wordpress, a CRUD website application such as the Medium website",
    url: "",
    tech: ["Vue", "Responsive"],
    pic: "Minimum.jpeg",
  },
  {
    title: "IngetIn",
    desc: "IngetIn is a website application for managing all your passwords",
    url: "",
    tech: ["React js", "Firebase", "Responsive"],
    pic: "ingetIn.jpg",
  },
  {
    title: "Coffee Me",
    desc: "Coffee Me is a E-Commerce Coffee shop website",
    url: "",
    tech: ["Vue Js", "Node Js", "Responsive"],
    pic: "CoffeeMe.jpg",
  },
  {
    title: "Bercerita",
    desc: "E-Book App",
    url: "",
    tech: ["React Native", "Android App"],
    pic: "unknown.jpeg",
  },
  {
    title: "KanBan",
    desc: "Visual Board to manage your work",
    url: "",
    tech: ["React Js", "Firebase"],
    pic: "unknown.jpeg",
  },
];
