export const projects = [
  {
    title: "Sumber Alam Bali",
    desc: "Toko Batu Alam Website",
    url: "http://www.sumberalambali.com",
    tech: "React js",
    pic: "sumberalam.jpeg",
  },
  {
    title: "Wedding Invitation",
    desc: "Undangan Pernikahan Online",
    url: "https://undanganku.github.io/vinosyofi/",
    tech: "React js",
    pic: "undanganku.jpeg",
  },
  {
    title: "Mini Wordpress",
    desc: "Simple CRUD Wordpress",
    url: "",
    tech: "Vue js",
    pic: "",
  },
  {
    title: "Rumah Tani",
    desc: "",
    url: "",
    tech: "Vue js",
    pic: "",
  },
  {
    title: "Bercerita",
    desc: "",
    url: "",
    tech: "React Native",
    pic: "",
  },
  {
    title: "Password Manager",
    desc: "",
    url: "",
    tech: "React js",
    pic: "",
  },
  {
    title: "Coffee Me",
    desc: "",
    url: "",
    tech: "Vue",
    pic: "",
  },
  {
    title: "KanBan",
    desc: "",
    url: "",
    tech: "React",
    pic: "",
  },
  {
    title: "Coffee Me",
    desc: "",
    url: "",
    tech: "Vue",
    pic: "",
  },
];
